### ISSUE TITLE
Not working for Chinese version

### ISSUE THREAD

**Issue by teymur1988** [niou-ns/homebridge-aqara-hub-lux#1]
Hi there, 
Thanks for the plugin, but I cannot get it to work! I've got a chinese version of aqara hub. 
I've extracted the token using Charles web proxy... however the plugin says cannot discover aqara hub at ip address, can u please help?

Regards

Teymur

**Comment by niou-ns** [comment]
Sorry, but I don't have any access to chinese version, so I can't do much here.

**Comment by niou-ns** [comment]
@teymur1988 I've (probably) added support for Chinese version - would you like to check if 1.1.0 works with it?

**Comment by niou-ns** [comment]
@teymur1988 I've got confirmation that it's working for Chinese version, so enjoy!
