### ISSUE TITLE
Including other Aqara lux sensors

### ISSUE THREAD

**Issue by ursusHU** [niou-ns/homebridge-aqara-hub-lux#2]
Hi,
Would it be possible to expose also Aqara motion sensor’s light sensor To HomeKit? It would be very useful to use it instead of timings.

**Comment by niou-ns** [comment]
Hey @ursusHU , I've tried to achieve that, but unfortunately it's not possible (not without any custom firmware, but it's not something which I'll be working on). That's why I came up with this plugin instead.
