### ISSUE TITLE
Still cannot get the token of the AqaraHub. Please help!

### ISSUE THREAD

**Issue by teymur1988** [niou-ns/homebridge-aqara-hub-lux#4]
Hi there,

I don't why, maybe my AqaraHub (chinese version) is special, but I'm not able to use the token that I retrieved from the device. It looks like it is being changed once the device is paired with the app. Here are the steps I follow:
I reset my device:

1) When the device is in AccessPoint mode I connect to it:
With packet sender I send the HEX "21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffffff" to the IP of the device (192.168.5.1) port 54321

2) I listen the traffic with Wireshark and the device replies:

`0000   f8 16 54 61 7f 01 50 ec 50 ed 88 8b 08 00 45 00   ..Ta..P.P.....E.
0010   00 3c d5 da 40 00 40 11 d9 20 c0 a8 05 01 c0 a8   .<..@.@.. ......
0020   05 64 d4 31 f4 01 00 28 b3 ca 21 31 00 20 00 00   .d.1...(..!1. ..
0030   00 00 10 71 ef fc 00 00 03 8f 50 61 77 45 76 41   ...q......PawEvA
0040   58 31 35 6c 73 72 32 32 61 71                     X15lsr22aq`

3) I take last 16 bytes `PawEvAX15lsr22aq` and convert them with https://www.rapidtables.com/convert/number/ascii-to-hex.html this tool and I get `50 61 77 45 76 41 58 31 35 6c 73 72 32 32 61 71` 

4) I remove the spaces and then I paste this `5061774576415831356c737232326171` in the plugin settings, save config and restart homebridge

5) Pair the device with the aqara app, add motion sensor so I get the light sensor as well

6) Homebridge log says 

Failed to discover aqara gateway at IP address, will try again in 30 seconds.

Can you please point out anything that I do wrong. THanks!

**Comment by niou-ns** [comment]
@teymur1988 Hi, try to use Xiaomi home app instead of Aqara and get the token out from apps database. https://github.com/Maxmudjon/com.xiaomi-miio/blob/master/docs/obtain_token.md <- method 1.
