### ISSUE TITLE
Optain token?

### ISSUE THREAD

**Issue by Bogdis** [niou-ns/homebridge-aqara-hub-lux#8]
Hello,

I don't use the Mi Home app so my Aqara Hub is not listed there and if I add the hub to mi home I need to reset the hub and I don't want to do that because I have 23 devices connected to it.

How do I get the token from the Aqara app?

thanks.

**Comment by Bogdis** [comment]
No one that can help me?

**Comment by codyc1515** [comment]
I am wondering the same and will hopefully be able to take a look at it soon.

**Comment by niou-ns** [comment]
@Bogdis have you tried https://github.com/Maxmudjon/Get_MiHome_devices_token/releases this app? Works like a charm on MacOS.
